export default {
    products: [
      {
        _id: '1',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '/images/n2.jpg',
        price: 60,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock:5,
      },
      {
        _id: '2',
        name: 'Fit Shirt',
        category: 'Shirts',
        image: '/images/n2.jpg',
        price: 50,
        brand: ' Nike',
        rating: 4.2,
        numReviews: 5,
        countInStock:6,
      },
      {
        _id: '3',
        name: 'Best Pants',
        category: 'Pants',
        image: '/images/n2.jpg',
        price: 70,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 8,
        countInStock:16,
      }, {
        _id: '4',
        name: 'Best Pants',
        category: 'Pants',
        image: '/images/n2.jpg',
        price: 70,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 8,
        countInStock:20,
      },
      {
        _id: '5',
        name: 'Best Pants',
        category: 'Pants',
        image: '/images/n2.jpg',
        price: 70,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 8,
        countInStock:3,
      },
      {
        _id: '6',
        name: 'Best Pants',
        category: 'Pants',
        image: '/images/n2.jpg',
        price: 70,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 8,
        countInStock:0,
      },
    ]
  }